In [3]:
import numpy as np

In [4]:
# Função softmax simples
def softmax(x):
    exp_x = np.exp(x - np.max(x))
    return exp_x / exp_x.sum(axis=-1, keepdims=True)


In [5]:
# Função que calcula a atenção simplificada
def self_attention(Q, K, V):
    # Similaridade (produto escalar entre Query e Key)
    scores = np.dot(Q, K.T)
    
    # Aplicar softmax para obter pesos normalizados (probabilidades)
    attention_weights = softmax(scores)
    
    # Multiplicar pesos pelos valores (Value)
    output = np.dot(attention_weights, V)
    
    return output, attention_weights

In [ ]:
# Nossa frase:
sentence = ["Maria", "gosta", "de", "matemática"]

# Para fins didáticos, criamos embeddings artificiais (dimensionais simplificadas = 3)
word_embeddings = {
    "Maria":      [1.0, 0.2, 0.4],
    "gosta":      [0.9, 0.1, 0.3],
    "de":         [0.1, 1.0, 0.7],
    "matemática": [0.8, 0.5, 0.9]
}

# Query representa "o que cada palavra busca".
# Key representa "o que cada palavra oferece às outras".
# Value é "a informação real de cada palavra".

In [8]:
# Montamos as matrizes Q, K e V a partir dos embeddings
Q = np.array([word_embeddings[word] for word in sentence])
K = np.array([word_embeddings[word] for word in sentence])
V = np.array([word_embeddings[word] for word in sentence])

# Executamos o mecanismo de atenção
output, attention_weights = self_attention(Q, K, V)

# Resultados:
print("Palavras:", sentence)
print("\nPesos de Atenção:\n", np.round(attention_weights, 2))
print("\nRepresentação final enriquecida por atenção:\n", np.round(output, 2))

Palavras: ['Maria', 'gosta', 'de', 'matemática']

Pesos de Atenção:
 [[0.29 0.25 0.16 0.31]
 [0.29 0.26 0.15 0.29]
 [0.16 0.13 0.4  0.3 ]
 [0.23 0.19 0.22 0.36]]

Representação final enriquecida por atenção:
 [[0.77 0.39 0.58]
 [0.78 0.39 0.57]
 [0.56 0.6  0.66]
 [0.71 0.47 0.63]]
